// Lezione 7/angular_project/delivery-project-angular/src/app/components/detail-card/detail-card.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-detail-card',
  templateUrl: './detail-card.component.html',
  styleUrls: ['./detail-card.component.scss'],
})
export class DetailCardComponent implements OnInit {
  @Input()
  detail: any = undefined;

  constructor() {}

  ngOnInit(): void {}
}

<!-- <div class="col-sm-6 col-lg-6 col-md-6"> -->
<div class="card mb-3">
  <div class="row no-gutters">
    <div class="col-md-8">
      <div class="card-body p-0 m-0">
        <div class="ml-auto">
          <p class="font-weight-bold card-title mb-1">
            {{ detail.title }}
          </p>
        </div>
        <p class="card-text mb-1">{{ detail.subtitle }}</p>
        <p class="card-text mb-1">
          <small class="price">{{ detail.reservation_items[0].price }} €</small>
        </p>
        <button class="btn d-button">+ Add to cart</button>
      </div>
    </div>
    <div class="col-md-4">
      <img
        src="https://raster-static.postmates.com/?url=https%3A%2F%2Fitems-static.postmates.com%2Fuploads%2Fmedia%2F83821a90-d3a8-593a-9726-e566d3c9471d%2F83821a90-d3a8-593a-9726-e566d3c9471d.jpg%3Fv%3D63779732459&quality=85&w=320&h=0&mode=auto&format=webp&v=4"
        class="card-img"
        alt="..."
      />
    </div>
  </div>
</div>
<!-- </div> -->

// Lezione 7/react_project/delivery_project_react/src/components/DetailCard/index.js

import React, { useState, useEffect } from 'react';
import { fetchRestaurantCategories } from '../../service/api';

const DetailTitle = (props) => {

  

    return (
        <>
            <div className="col-sm-6 col-lg-6 col-md-6">
                <div className="card mb-3">
                    <div className="row no-gutters">

                        <div className="col-md-8">
                            <div className="card-body p-0 m-0 ">
                                <div className="ml-auto">
                                    <p className="font-weight-bold card-title mb-1">{props.title}</p>

                                </div>
                                <p className="card-text mb-1">{props.subtitle}</p>
                                <p className="card-text mb-1"><small className="price">{props.price} €</small></p>

                            </div>
                        </div>
                        <div className="col-md-4">
                            <img src="https://raster-static.postmates.com/?url=https%3A%2F%2Fitems-static.postmates.com%2Fuploads%2Fmedia%2F83821a90-d3a8-593a-9726-e566d3c9471d%2F83821a90-d3a8-593a-9726-e566d3c9471d.jpg%3Fv%3D63779732459&quality=85&w=320&h=0&mode=auto&format=webp&v=4" className="card-img" alt="..." />
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
};


export default DetailTitle;
